In [48]:
import run_info_utils

In [49]:
df = run_info_utils.get_df_run_info()

In [50]:
df.head()

,all_correct_stop,batch_size,carry_list,confidence_prob,dev/carry-0/early_stopping/accuracy,dev/carry-1/early_stopping/accuracy,dev/carry-2/early_stopping/accuracy,dev/carry-3/early_stopping/accuracy,dev/carry-4/early_stopping/accuracy,dev/early_stopping/max_correct_answer_step,...,time/last_time,time/running_time,time/start_time,train_dev_test_ratio,train_set_size,train_set_size/carry-0,train_set_size/carry-1,train_set_size/carry-2,train_set_size/carry-3,train_set_size/carry-4
0,True,32,NaN,0.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaT,NaT,"(1.0, 0, 0)",256,81.0,54.0,52.0,42.0,27.0
1,True,32,NaN,0.9,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaT,NaT,"(1.0, 0, 0)",256,81.0,54.0,52.0,42.0,27.0
2,True,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaT,NaT,NaN,136,NaN,NaN,NaN,NaN,NaN
3,True,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaT,NaT,NaN,256,NaN,NaN,NaN,NaN,NaN
4,True,32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaT,NaT,NaT,NaN,240,NaN,NaN,NaN,NaN,NaN

In [51]:
# print(list(df.columns))

In [52]:
experiment_name = 'jordan_cp9_add_sub_maxstep'
df = df.loc[df['experiment_name'] == experiment_name]

cols = ['run_id', 'operator', 'rnn_type', 'confidence_prob', 'operand_bits', 'hidden_activation', 'max_steps',
'dev/last_carry-0_mean_correct_answer_step', 
'dev/last_carry-1_mean_correct_answer_step', 
'dev/last_carry-2_mean_correct_answer_step', 
'dev/last_carry-3_mean_correct_answer_step', 
'dev/last_carry-4_mean_correct_answer_step', 
'dev/last_mean_correct_answer_step', 'dev/last_accuracy']
df = df[cols]

In [53]:
df = df.loc[df['dev/last_accuracy'] == 1.0]

In [54]:
df.shape

(1151, 14)

In [55]:
df_add_jordan_9_relu_maxstep10 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 10')
df_sub_jordan_9_relu_maxstep10 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 10')
df_add_jordan_9_relu_maxstep20 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 20')
df_sub_jordan_9_relu_maxstep20 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 20')
df_add_jordan_9_relu_maxstep30 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 30')
df_sub_jordan_9_relu_maxstep30 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 30')
df_add_jordan_9_relu_maxstep40 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 40')
df_sub_jordan_9_relu_maxstep40 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 40')
df_add_jordan_9_relu_maxstep50 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 50')
df_sub_jordan_9_relu_maxstep50 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 50')
df_add_jordan_9_relu_maxstep60 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 60')
df_sub_jordan_9_relu_maxstep60 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 60')
df_add_jordan_9_relu_maxstep90 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "relu"').query('max_steps == 90')


df_add_jordan_9_tanh_maxstep10 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 10')
df_sub_jordan_9_tanh_maxstep10 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 10')
df_add_jordan_9_tanh_maxstep20 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 20')
df_sub_jordan_9_tanh_maxstep20 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 20')
df_add_jordan_9_tanh_maxstep30 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 30')
df_sub_jordan_9_tanh_maxstep30 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 30')
df_add_jordan_9_tanh_maxstep40 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 40')
df_sub_jordan_9_tanh_maxstep40 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 40')
df_add_jordan_9_tanh_maxstep50 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 50')
df_sub_jordan_9_tanh_maxstep50 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 50')
df_add_jordan_9_tanh_maxstep60 = df.query('operator == "add"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 60')
df_sub_jordan_9_tanh_maxstep60 = df.query('operator == "subtract"').query('rnn_type == "jordan"').query('confidence_prob == 0.9').query('hidden_activation == "tanh"').query('max_steps == 60')

In [58]:
print(df_add_jordan_9_relu_maxstep10.shape)
print(df_sub_jordan_9_relu_maxstep10.shape)
print(df_add_jordan_9_relu_maxstep20.shape)
print(df_sub_jordan_9_relu_maxstep20.shape)
print(df_add_jordan_9_relu_maxstep30.shape)
print(df_sub_jordan_9_relu_maxstep30.shape)
print(df_add_jordan_9_relu_maxstep40.shape)
print(df_sub_jordan_9_relu_maxstep40.shape)
print(df_add_jordan_9_relu_maxstep50.shape)
print(df_sub_jordan_9_relu_maxstep50.shape)
print(df_add_jordan_9_relu_maxstep60.shape)
print(df_sub_jordan_9_relu_maxstep60.shape)
print(df_add_jordan_9_relu_maxstep90.shape)

(100, 14)
(30, 14)
(100, 14)
(30, 14)
(100, 14)
(30, 14)
(30, 14)
(30, 14)
(102, 14)
(30, 14)
(102, 14)
(30, 14)
(60, 14)

In [59]:
print(df_add_jordan_9_tanh_maxstep10.shape)
print(df_sub_jordan_9_tanh_maxstep10.shape)
print(df_add_jordan_9_tanh_maxstep20.shape)
print(df_sub_jordan_9_tanh_maxstep20.shape)
print(df_add_jordan_9_tanh_maxstep30.shape)
print(df_sub_jordan_9_tanh_maxstep30.shape)
print(df_add_jordan_9_tanh_maxstep40.shape)
print(df_sub_jordan_9_tanh_maxstep40.shape)
print(df_add_jordan_9_tanh_maxstep50.shape)
print(df_sub_jordan_9_tanh_maxstep50.shape)
print(df_add_jordan_9_tanh_maxstep60.shape)
print(df_sub_jordan_9_tanh_maxstep60.shape)

(37, 14)
(40, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)
(30, 14)

# Result

In [60]:
df_add_jordan_9_relu_maxstep40.describe()

,confidence_prob,operand_bits,max_steps,dev/last_carry-0_mean_correct_answer_step,dev/last_carry-1_mean_correct_answer_step,dev/last_carry-2_mean_correct_answer_step,dev/last_carry-3_mean_correct_answer_step,dev/last_carry-4_mean_correct_answer_step,dev/last_mean_correct_answer_step,dev/last_accuracy
count,3.000000e+01,30.0,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,9.000000e-01,4.0,40.0,2.428395,4.304938,8.871154,13.933333,20.608642,7.937891,1.0
std,2.258405e-16,0.0,0.0,1.441839,2.770914,4.956138,7.701149,9.403478,3.598127,0.0
min,9.000000e-01,4.0,40.0,0.802469,1.222222,1.692308,2.047619,2.370370,1.691406,1.0
25%,9.000000e-01,4.0,40.0,1.385802,2.337963,5.562500,8.809524,14.490741,5.565430,1.0
50%,9.000000e-01,4.0,40.0,1.864198,3.259259,7.653846,12.321428,22.629629,7.587891,1.0
75%,9.000000e-01,4.0,40.0,3.453704,6.032407,11.442308,19.619047,28.305555,10.259766,1.0
max,9.000000e-01,4.0,40.0,6.370370,11.481482,23.076923,29.857143,39.000000,16.605469,1.0

In [61]:
df_sub_jordan_9_relu_maxstep40.describe()

,confidence_prob,operand_bits,max_steps,dev/last_carry-0_mean_correct_answer_step,dev/last_carry-1_mean_correct_answer_step,dev/last_carry-2_mean_correct_answer_step,dev/last_carry-3_mean_correct_answer_step,dev/last_carry-4_mean_correct_answer_step,dev/last_mean_correct_answer_step,dev/last_accuracy
count,3.000000e+01,30.0,30.0,30.000000,30.000000,30.000000,30.000000,0.0,30.000000,30.0
mean,9.000000e-01,4.0,40.0,2.436214,8.538272,18.387719,29.874074,NaN,7.691912,1.0
std,2.258405e-16,0.0,0.0,1.918958,5.948510,7.776826,8.827360,NaN,3.451691,0.0
min,9.000000e-01,4.0,40.0,0.604938,1.518519,2.947368,8.000000,NaN,2.191176,1.0
25%,9.000000e-01,4.0,40.0,1.120370,3.342593,13.750000,23.916667,NaN,5.509191,1.0
50%,9.000000e-01,4.0,40.0,1.765432,7.185185,17.394736,32.333332,NaN,6.845588,1.0
75%,9.000000e-01,4.0,40.0,2.876543,10.500000,24.302631,36.666667,NaN,9.786765,1.0
max,9.000000e-01,4.0,40.0,8.567902,22.851852,37.263157,39.000000,NaN,17.426470,1.0

# Export as CSV

## Functionalize

In [62]:
import pandas as pd
import numpy as np
import data_utils 
from utils import create_dir
from os.path import join

def get_csv_df(df, filename, experiment_name):
    # Get configurations
    n_rows = df.shape[0]
    operator = df['operator'].iloc[0]
    operand_digits = df['operand_bits'].iloc[0]
    carry_list = list(data_utils.import_carry_datasets(operand_digits, operator).keys())
    
    # Gather for each 
    csv_df_list = list()
    for carries in carry_list:
        col = 'dev/last_carry-{}_mean_correct_answer_step'.format(carries)
        csv_df = pd.DataFrame(data={'mean_anwer_steps':df[col], 'carries':np.full((n_rows), carries)})
        csv_df_list.append(csv_df)
    csv_df = pd.concat(csv_df_list, ignore_index=True)
    
    # Change the order of columns
    csv_df = csv_df[['mean_anwer_steps', 'carries']]
    
    # Create dir
    dir_to_save = join('result_statistics', experiment_name)
    create_dir(dir_to_save)
    
    # Save the dataframe to a CSV file.
    csv_df.to_csv(join(dir_to_save, filename), index=False)

In [63]:
experiment_name = 'jordan_cp9_add_sub_maxstep'

In [66]:
get_csv_df(df_add_jordan_9_relu_maxstep10, 'df_add_jordan_9_relu_maxstep10.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep10, 'df_sub_jordan_9_relu_maxstep10.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep20, 'df_add_jordan_9_relu_maxstep20.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep20, 'df_sub_jordan_9_relu_maxstep20.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep30, 'df_add_jordan_9_relu_maxstep30.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep30, 'df_sub_jordan_9_relu_maxstep30.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep40, 'df_add_jordan_9_relu_maxstep40.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep40, 'df_sub_jordan_9_relu_maxstep40.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep50, 'df_add_jordan_9_relu_maxstep50.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep50, 'df_sub_jordan_9_relu_maxstep50.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep60, 'df_add_jordan_9_relu_maxstep60.csv', experiment_name)
get_csv_df(df_sub_jordan_9_relu_maxstep60, 'df_sub_jordan_9_relu_maxstep60.csv', experiment_name)
get_csv_df(df_add_jordan_9_relu_maxstep90, 'df_add_jordan_9_relu_maxstep90.csv', experiment_name)

In [65]:
get_csv_df(df_add_jordan_9_tanh_maxstep10, 'df_add_jordan_9_tanh_maxstep10.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep10, 'df_sub_jordan_9_tanh_maxstep10.csv', experiment_name)
get_csv_df(df_add_jordan_9_tanh_maxstep20, 'df_add_jordan_9_tanh_maxstep20.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep20, 'df_sub_jordan_9_tanh_maxstep20.csv', experiment_name)
get_csv_df(df_add_jordan_9_tanh_maxstep30, 'df_add_jordan_9_tanh_maxstep30.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep30, 'df_sub_jordan_9_tanh_maxstep30.csv', experiment_name)
get_csv_df(df_add_jordan_9_tanh_maxstep40, 'df_add_jordan_9_tanh_maxstep40.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep40, 'df_sub_jordan_9_tanh_maxstep40.csv', experiment_name)
get_csv_df(df_add_jordan_9_tanh_maxstep50, 'df_add_jordan_9_tanh_maxstep50.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep50, 'df_sub_jordan_9_tanh_maxstep50.csv', experiment_name)
get_csv_df(df_add_jordan_9_tanh_maxstep60, 'df_add_jordan_9_tanh_maxstep60.csv', experiment_name)
get_csv_df(df_sub_jordan_9_tanh_maxstep60, 'df_sub_jordan_9_tanh_maxstep60.csv', experiment_name)